# Scheduling worker jobs
send_private_message_notifications:
  every:
    - "30s"
  class: MessageNotifications
  description: "This job finds all messages on recent activity and sends their receivers the message notifications"

send_join_request_notifications:
  every:
    - "30s"
  class: JoinRequestNotifications
  description: "This job finds all join requests on recent activity and sends the space admins or users the message notifications"

send_processed_join_request_notifications:
  every:
    - "30s"
  class: ProcessedJoinRequestNotifications
  description: "This job finds all join requests accepted on recent activity and sends to the users the notifications"

send_invitations:
  every:
    - "30s"
  class: Invitations
  description: "Finds all invitations still not sent and sends them"
